### ISSUE TITLE
Design The Interface

### ISSUE THREAD

**Issue by algoives** [algoives/FeedbackApp#2]

**Comment by algoives** [comment]
Design a user interface of the app using the guidlines.
(https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/)

**Comment by Ives-algorhym** [comment]
I having problems whit the lay out ,I don't understand constrains.

**Comment by Ives-algorhym** [comment]
I create a sample of the buttons and text fields in the sign in page
need to review how to creat custom classes to create my own library

**Comment by algoives** [comment]
Interface updated
